version: "3.9"

services:
  postgres-test:
    image: postgres:16-alpine
    container_name: helados-sofis-test-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: helados_sofis_test
    ports:
      - "5432:5432"
    volumes:
      - helados_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  helados_test_data:
